apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: characteristic-silkworm-dotnet-basic
  janus-idp.io/tekton: characteristic-silkworm-dotnet-basic
  backstage.io/kubernetes-id: characteristic-silkworm-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: characteristic-silkworm-dotnet-basic
resources: 
- deployment.yaml
- route.yaml
- service.yaml
